name: Dansk Skole
favicon: null
layout_spectrum: 0.0056
typography_spectrum: 0.16566
title: Den Danske Skole e.V.
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#658dcc'
    - '#080808'
    - '#dadae6'
    - '#985e43'
    - '#b63438'
  brandStrength: 0
  lightness: 0.5
  saturation: 0
  rhythmicContrast: 0.5
purpose: []
